/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sample.avro.bean;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OutputCanInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6801644888079277817L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OutputCanInfo\",\"namespace\":\"org.apache.avro.example.bean\",\"fields\":[{\"name\":\"canId\",\"type\":\"string\"},{\"name\":\"canTime\",\"type\":[\"long\",\"null\"]},{\"name\":\"c001_dummy15\",\"type\":[\"long\",\"null\"]},{\"name\":\"c001_dummy16\",\"type\":[\"long\",\"null\"]},{\"name\":\"c001_dummy17\",\"type\":[\"long\",\"null\"]},{\"name\":\"c022_dummy15\",\"type\":[\"long\",\"null\"]},{\"name\":\"c022_dummy16\",\"type\":[\"long\",\"null\"]},{\"name\":\"c022_dummy17\",\"type\":[\"long\",\"null\"]},{\"name\":\"c022_dummy18\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OutputCanInfo> ENCODER =
      new BinaryMessageEncoder<OutputCanInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OutputCanInfo> DECODER =
      new BinaryMessageDecoder<OutputCanInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OutputCanInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OutputCanInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OutputCanInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OutputCanInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OutputCanInfo from a ByteBuffer. */
  public static OutputCanInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence canId;
  @Deprecated public java.lang.Long canTime;
  @Deprecated public java.lang.Long c001_dummy15;
  @Deprecated public java.lang.Long c001_dummy16;
  @Deprecated public java.lang.Long c001_dummy17;
  @Deprecated public java.lang.Long c022_dummy15;
  @Deprecated public java.lang.Long c022_dummy16;
  @Deprecated public java.lang.Long c022_dummy17;
  @Deprecated public java.lang.Long c022_dummy18;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OutputCanInfo() {}

  /**
   * All-args constructor.
   * @param canId The new value for canId
   * @param canTime The new value for canTime
   * @param c001_dummy15 The new value for c001_dummy15
   * @param c001_dummy16 The new value for c001_dummy16
   * @param c001_dummy17 The new value for c001_dummy17
   * @param c022_dummy15 The new value for c022_dummy15
   * @param c022_dummy16 The new value for c022_dummy16
   * @param c022_dummy17 The new value for c022_dummy17
   * @param c022_dummy18 The new value for c022_dummy18
   */
  public OutputCanInfo(java.lang.CharSequence canId, java.lang.Long canTime, java.lang.Long c001_dummy15, java.lang.Long c001_dummy16, java.lang.Long c001_dummy17, java.lang.Long c022_dummy15, java.lang.Long c022_dummy16, java.lang.Long c022_dummy17, java.lang.Long c022_dummy18) {
    this.canId = canId;
    this.canTime = canTime;
    this.c001_dummy15 = c001_dummy15;
    this.c001_dummy16 = c001_dummy16;
    this.c001_dummy17 = c001_dummy17;
    this.c022_dummy15 = c022_dummy15;
    this.c022_dummy16 = c022_dummy16;
    this.c022_dummy17 = c022_dummy17;
    this.c022_dummy18 = c022_dummy18;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return canId;
    case 1: return canTime;
    case 2: return c001_dummy15;
    case 3: return c001_dummy16;
    case 4: return c001_dummy17;
    case 5: return c022_dummy15;
    case 6: return c022_dummy16;
    case 7: return c022_dummy17;
    case 8: return c022_dummy18;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: canId = (java.lang.CharSequence)value$; break;
    case 1: canTime = (java.lang.Long)value$; break;
    case 2: c001_dummy15 = (java.lang.Long)value$; break;
    case 3: c001_dummy16 = (java.lang.Long)value$; break;
    case 4: c001_dummy17 = (java.lang.Long)value$; break;
    case 5: c022_dummy15 = (java.lang.Long)value$; break;
    case 6: c022_dummy16 = (java.lang.Long)value$; break;
    case 7: c022_dummy17 = (java.lang.Long)value$; break;
    case 8: c022_dummy18 = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'canId' field.
   * @return The value of the 'canId' field.
   */
  public java.lang.CharSequence getCanId() {
    return canId;
  }

  /**
   * Sets the value of the 'canId' field.
   * @param value the value to set.
   */
  public void setCanId(java.lang.CharSequence value) {
    this.canId = value;
  }

  /**
   * Gets the value of the 'canTime' field.
   * @return The value of the 'canTime' field.
   */
  public java.lang.Long getCanTime() {
    return canTime;
  }

  /**
   * Sets the value of the 'canTime' field.
   * @param value the value to set.
   */
  public void setCanTime(java.lang.Long value) {
    this.canTime = value;
  }

  /**
   * Gets the value of the 'c001_dummy15' field.
   * @return The value of the 'c001_dummy15' field.
   */
  public java.lang.Long getC001Dummy15() {
    return c001_dummy15;
  }

  /**
   * Sets the value of the 'c001_dummy15' field.
   * @param value the value to set.
   */
  public void setC001Dummy15(java.lang.Long value) {
    this.c001_dummy15 = value;
  }

  /**
   * Gets the value of the 'c001_dummy16' field.
   * @return The value of the 'c001_dummy16' field.
   */
  public java.lang.Long getC001Dummy16() {
    return c001_dummy16;
  }

  /**
   * Sets the value of the 'c001_dummy16' field.
   * @param value the value to set.
   */
  public void setC001Dummy16(java.lang.Long value) {
    this.c001_dummy16 = value;
  }

  /**
   * Gets the value of the 'c001_dummy17' field.
   * @return The value of the 'c001_dummy17' field.
   */
  public java.lang.Long getC001Dummy17() {
    return c001_dummy17;
  }

  /**
   * Sets the value of the 'c001_dummy17' field.
   * @param value the value to set.
   */
  public void setC001Dummy17(java.lang.Long value) {
    this.c001_dummy17 = value;
  }

  /**
   * Gets the value of the 'c022_dummy15' field.
   * @return The value of the 'c022_dummy15' field.
   */
  public java.lang.Long getC022Dummy15() {
    return c022_dummy15;
  }

  /**
   * Sets the value of the 'c022_dummy15' field.
   * @param value the value to set.
   */
  public void setC022Dummy15(java.lang.Long value) {
    this.c022_dummy15 = value;
  }

  /**
   * Gets the value of the 'c022_dummy16' field.
   * @return The value of the 'c022_dummy16' field.
   */
  public java.lang.Long getC022Dummy16() {
    return c022_dummy16;
  }

  /**
   * Sets the value of the 'c022_dummy16' field.
   * @param value the value to set.
   */
  public void setC022Dummy16(java.lang.Long value) {
    this.c022_dummy16 = value;
  }

  /**
   * Gets the value of the 'c022_dummy17' field.
   * @return The value of the 'c022_dummy17' field.
   */
  public java.lang.Long getC022Dummy17() {
    return c022_dummy17;
  }

  /**
   * Sets the value of the 'c022_dummy17' field.
   * @param value the value to set.
   */
  public void setC022Dummy17(java.lang.Long value) {
    this.c022_dummy17 = value;
  }

  /**
   * Gets the value of the 'c022_dummy18' field.
   * @return The value of the 'c022_dummy18' field.
   */
  public java.lang.Long getC022Dummy18() {
    return c022_dummy18;
  }

  /**
   * Sets the value of the 'c022_dummy18' field.
   * @param value the value to set.
   */
  public void setC022Dummy18(java.lang.Long value) {
    this.c022_dummy18 = value;
  }

  /**
   * Creates a new OutputCanInfo RecordBuilder.
   * @return A new OutputCanInfo RecordBuilder
   */
  public static sample.avro.bean.OutputCanInfo.Builder newBuilder() {
    return new sample.avro.bean.OutputCanInfo.Builder();
  }

  /**
   * Creates a new OutputCanInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OutputCanInfo RecordBuilder
   */
  public static sample.avro.bean.OutputCanInfo.Builder newBuilder(sample.avro.bean.OutputCanInfo.Builder other) {
    return new sample.avro.bean.OutputCanInfo.Builder(other);
  }

  /**
   * Creates a new OutputCanInfo RecordBuilder by copying an existing OutputCanInfo instance.
   * @param other The existing instance to copy.
   * @return A new OutputCanInfo RecordBuilder
   */
  public static sample.avro.bean.OutputCanInfo.Builder newBuilder(sample.avro.bean.OutputCanInfo other) {
    return new sample.avro.bean.OutputCanInfo.Builder(other);
  }

  /**
   * RecordBuilder for OutputCanInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OutputCanInfo>
    implements org.apache.avro.data.RecordBuilder<OutputCanInfo> {

    private java.lang.CharSequence canId;
    private java.lang.Long canTime;
    private java.lang.Long c001_dummy15;
    private java.lang.Long c001_dummy16;
    private java.lang.Long c001_dummy17;
    private java.lang.Long c022_dummy15;
    private java.lang.Long c022_dummy16;
    private java.lang.Long c022_dummy17;
    private java.lang.Long c022_dummy18;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(sample.avro.bean.OutputCanInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.canId)) {
        this.canId = data().deepCopy(fields()[0].schema(), other.canId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.canTime)) {
        this.canTime = data().deepCopy(fields()[1].schema(), other.canTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.c001_dummy15)) {
        this.c001_dummy15 = data().deepCopy(fields()[2].schema(), other.c001_dummy15);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.c001_dummy16)) {
        this.c001_dummy16 = data().deepCopy(fields()[3].schema(), other.c001_dummy16);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.c001_dummy17)) {
        this.c001_dummy17 = data().deepCopy(fields()[4].schema(), other.c001_dummy17);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.c022_dummy15)) {
        this.c022_dummy15 = data().deepCopy(fields()[5].schema(), other.c022_dummy15);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.c022_dummy16)) {
        this.c022_dummy16 = data().deepCopy(fields()[6].schema(), other.c022_dummy16);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.c022_dummy17)) {
        this.c022_dummy17 = data().deepCopy(fields()[7].schema(), other.c022_dummy17);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.c022_dummy18)) {
        this.c022_dummy18 = data().deepCopy(fields()[8].schema(), other.c022_dummy18);
        fieldSetFlags()[8] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OutputCanInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(sample.avro.bean.OutputCanInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.canId)) {
        this.canId = data().deepCopy(fields()[0].schema(), other.canId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.canTime)) {
        this.canTime = data().deepCopy(fields()[1].schema(), other.canTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.c001_dummy15)) {
        this.c001_dummy15 = data().deepCopy(fields()[2].schema(), other.c001_dummy15);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.c001_dummy16)) {
        this.c001_dummy16 = data().deepCopy(fields()[3].schema(), other.c001_dummy16);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.c001_dummy17)) {
        this.c001_dummy17 = data().deepCopy(fields()[4].schema(), other.c001_dummy17);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.c022_dummy15)) {
        this.c022_dummy15 = data().deepCopy(fields()[5].schema(), other.c022_dummy15);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.c022_dummy16)) {
        this.c022_dummy16 = data().deepCopy(fields()[6].schema(), other.c022_dummy16);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.c022_dummy17)) {
        this.c022_dummy17 = data().deepCopy(fields()[7].schema(), other.c022_dummy17);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.c022_dummy18)) {
        this.c022_dummy18 = data().deepCopy(fields()[8].schema(), other.c022_dummy18);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'canId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCanId() {
      return canId;
    }

    /**
      * Sets the value of the 'canId' field.
      * @param value The value of 'canId'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setCanId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.canId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'canId' field has been set.
      * @return True if the 'canId' field has been set, false otherwise.
      */
    public boolean hasCanId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'canId' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearCanId() {
      canId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'canTime' field.
      * @return The value.
      */
    public java.lang.Long getCanTime() {
      return canTime;
    }

    /**
      * Sets the value of the 'canTime' field.
      * @param value The value of 'canTime'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setCanTime(java.lang.Long value) {
      validate(fields()[1], value);
      this.canTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'canTime' field has been set.
      * @return True if the 'canTime' field has been set, false otherwise.
      */
    public boolean hasCanTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'canTime' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearCanTime() {
      canTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'c001_dummy15' field.
      * @return The value.
      */
    public java.lang.Long getC001Dummy15() {
      return c001_dummy15;
    }

    /**
      * Sets the value of the 'c001_dummy15' field.
      * @param value The value of 'c001_dummy15'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC001Dummy15(java.lang.Long value) {
      validate(fields()[2], value);
      this.c001_dummy15 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'c001_dummy15' field has been set.
      * @return True if the 'c001_dummy15' field has been set, false otherwise.
      */
    public boolean hasC001Dummy15() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'c001_dummy15' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC001Dummy15() {
      c001_dummy15 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'c001_dummy16' field.
      * @return The value.
      */
    public java.lang.Long getC001Dummy16() {
      return c001_dummy16;
    }

    /**
      * Sets the value of the 'c001_dummy16' field.
      * @param value The value of 'c001_dummy16'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC001Dummy16(java.lang.Long value) {
      validate(fields()[3], value);
      this.c001_dummy16 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'c001_dummy16' field has been set.
      * @return True if the 'c001_dummy16' field has been set, false otherwise.
      */
    public boolean hasC001Dummy16() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'c001_dummy16' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC001Dummy16() {
      c001_dummy16 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'c001_dummy17' field.
      * @return The value.
      */
    public java.lang.Long getC001Dummy17() {
      return c001_dummy17;
    }

    /**
      * Sets the value of the 'c001_dummy17' field.
      * @param value The value of 'c001_dummy17'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC001Dummy17(java.lang.Long value) {
      validate(fields()[4], value);
      this.c001_dummy17 = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'c001_dummy17' field has been set.
      * @return True if the 'c001_dummy17' field has been set, false otherwise.
      */
    public boolean hasC001Dummy17() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'c001_dummy17' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC001Dummy17() {
      c001_dummy17 = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'c022_dummy15' field.
      * @return The value.
      */
    public java.lang.Long getC022Dummy15() {
      return c022_dummy15;
    }

    /**
      * Sets the value of the 'c022_dummy15' field.
      * @param value The value of 'c022_dummy15'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC022Dummy15(java.lang.Long value) {
      validate(fields()[5], value);
      this.c022_dummy15 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'c022_dummy15' field has been set.
      * @return True if the 'c022_dummy15' field has been set, false otherwise.
      */
    public boolean hasC022Dummy15() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'c022_dummy15' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC022Dummy15() {
      c022_dummy15 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'c022_dummy16' field.
      * @return The value.
      */
    public java.lang.Long getC022Dummy16() {
      return c022_dummy16;
    }

    /**
      * Sets the value of the 'c022_dummy16' field.
      * @param value The value of 'c022_dummy16'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC022Dummy16(java.lang.Long value) {
      validate(fields()[6], value);
      this.c022_dummy16 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'c022_dummy16' field has been set.
      * @return True if the 'c022_dummy16' field has been set, false otherwise.
      */
    public boolean hasC022Dummy16() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'c022_dummy16' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC022Dummy16() {
      c022_dummy16 = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'c022_dummy17' field.
      * @return The value.
      */
    public java.lang.Long getC022Dummy17() {
      return c022_dummy17;
    }

    /**
      * Sets the value of the 'c022_dummy17' field.
      * @param value The value of 'c022_dummy17'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC022Dummy17(java.lang.Long value) {
      validate(fields()[7], value);
      this.c022_dummy17 = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'c022_dummy17' field has been set.
      * @return True if the 'c022_dummy17' field has been set, false otherwise.
      */
    public boolean hasC022Dummy17() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'c022_dummy17' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC022Dummy17() {
      c022_dummy17 = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'c022_dummy18' field.
      * @return The value.
      */
    public java.lang.Long getC022Dummy18() {
      return c022_dummy18;
    }

    /**
      * Sets the value of the 'c022_dummy18' field.
      * @param value The value of 'c022_dummy18'.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder setC022Dummy18(java.lang.Long value) {
      validate(fields()[8], value);
      this.c022_dummy18 = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'c022_dummy18' field has been set.
      * @return True if the 'c022_dummy18' field has been set, false otherwise.
      */
    public boolean hasC022Dummy18() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'c022_dummy18' field.
      * @return This builder.
      */
    public sample.avro.bean.OutputCanInfo.Builder clearC022Dummy18() {
      c022_dummy18 = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OutputCanInfo build() {
      try {
        OutputCanInfo record = new OutputCanInfo();
        record.canId = fieldSetFlags()[0] ? this.canId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.canTime = fieldSetFlags()[1] ? this.canTime : (java.lang.Long) defaultValue(fields()[1]);
        record.c001_dummy15 = fieldSetFlags()[2] ? this.c001_dummy15 : (java.lang.Long) defaultValue(fields()[2]);
        record.c001_dummy16 = fieldSetFlags()[3] ? this.c001_dummy16 : (java.lang.Long) defaultValue(fields()[3]);
        record.c001_dummy17 = fieldSetFlags()[4] ? this.c001_dummy17 : (java.lang.Long) defaultValue(fields()[4]);
        record.c022_dummy15 = fieldSetFlags()[5] ? this.c022_dummy15 : (java.lang.Long) defaultValue(fields()[5]);
        record.c022_dummy16 = fieldSetFlags()[6] ? this.c022_dummy16 : (java.lang.Long) defaultValue(fields()[6]);
        record.c022_dummy17 = fieldSetFlags()[7] ? this.c022_dummy17 : (java.lang.Long) defaultValue(fields()[7]);
        record.c022_dummy18 = fieldSetFlags()[8] ? this.c022_dummy18 : (java.lang.Long) defaultValue(fields()[8]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OutputCanInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<OutputCanInfo>)MODEL$.createDatumWriter(SCHEMA$);

//  @Override public void writeExternal(java.io.ObjectOutput out)
//    throws java.io.IOException {
//    WRITER$.write(this, SpecificData.getEncoder(out));
//  }
//
//  @SuppressWarnings("unchecked")
//  private static final org.apache.avro.io.DatumReader<OutputCanInfo>
//    READER$ = (org.apache.avro.io.DatumReader<OutputCanInfo>)MODEL$.createDatumReader(SCHEMA$);
//
//  @Override public void readExternal(java.io.ObjectInput in)
//    throws java.io.IOException {
//    READER$.read(this, SpecificData.getDecoder(in));
//  }

}
